apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kustomize.component: metadata
configMapGenerator:
- name: metadata-db-parameters
  envs:
  - params.env
bases:
- ../../base
patchesStrategicMerge:
- metadata-deployment.yaml