apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xgboost-operator
  template:
    metadata:
      labels:
        app: xgboost-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubeflow
                operator: In
                values:
                - "true"
      containers:
      - name: xgboost-operator
        command:
        - /root/manager
        - -mode=in-cluster
        image: gcr.io/kubeflow-images-public/xgboost-operator:v0.1.0
        imagePullPolicy: IfNotPresent
      serviceAccountName: service-account
