apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: knative-serving
resources:
- ../../knative-serving-crds/base
- ../../knative-serving-crds/overlays/application
- ../../knative-serving-install/base/gateway.yaml
- ../../knative-serving-install/base/cluster-role.yaml
- ../../knative-serving-install/base/cluster-role-binding.yaml
- ../../knative-serving-install/base/service-role.yaml
- ../../knative-serving-install/base/service-role-binding.yaml
- ../../knative-serving-install/base/config-map.yaml
- ../../knative-serving-install/base/deployment.yaml
- ../../knative-serving-install/base/secret.yaml
- ../../knative-serving-install/base/service-account.yaml
- ../../knative-serving-install/base/service.yaml
- ../../knative-serving-install/base/image.yaml
- ../../knative-serving-install/base/hpa.yaml
- ../../knative-serving-install/base/webhook-configuration.yaml
- ../../knative-serving-install/overlays/application
commonLabels:
  kustomize.component: knative
  app.kubernetes.io/component: knative-serving-install
  app.kubernetes.io/name: knative-serving-install
images:
- name: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  newName: ai.tencentmusic.com/tme-public/knative
  newTag: serving-activator
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  newName: ai.tencentmusic.com/tme-public/knative
  newTag: serving-autoscaler
- name: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  newName: ai.tencentmusic.com/tme-public/knative
  newTag: serving-webhook
- name: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  newName: ai.tencentmusic.com/tme-public/knative
  newTag: serving-controller
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  newName: ai.tencentmusic.com/tme-public/knative
  newTag: net-istio-controller
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  newName: ai.tencentmusic.com/tme-public/knative
  newTag: net-istio-webhook

